# Generated by Django 4.2.5 on 2024-05-21 22:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('categoria', models.CharField(choices=[('EBOOK', 'E-book'), ('FISICO', 'Físico')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugestaoLiteraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('categoria_desejada', models.CharField(max_length=100)),
                ('autores_preferidos', models.TextField()),
                ('temas_preferidos', models.TextField()),
                ('livros_sugeridos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('BIBLIOTECARIO', 'Bibliotecário'), ('AUTOR', 'Autor'), ('ADMIN', 'Administrador'), ('USUARIO', 'Usuário')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('qtd_paginas', models.PositiveIntegerField()),
                ('numero_edicao', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_estoque', models.PositiveIntegerField()),
                ('estrelas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('imagem_capa', models.ImageField(upload_to='livros_capas/')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='DISPONIVEL', max_length=20)),
                ('autorFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.usuario')),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.categorialivro')),
                ('formatoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.formato')),
                ('generoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_realizada', models.DateTimeField(blank=True, null=True)),
                ('valor_total_emprestimo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
                ('livroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.livro')),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.usuario')),
            ],
        ),
    ]
