# Generated by Django 4.2.5 on 2024-05-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.emprestimo')),
                ('livroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.livro')),
            ],
        ),
        migrations.DeleteModel(
            name='SugestaoLiteraria',
        ),
    ]
